
/*
 VISIBILITY
 */
export const TOGGLE_APPLICATIONS_MENU = 'TOGGLE_APPLICATIONS_MENU';
export const SHOW_APPLICATIONS_MENU = 'SHOW_APPLICATIONS_MENU';

export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU';

export const TOGGLE_BUSINESS_PARTNER_MENU = 'TOGGLE_BUSINESS_PARTNER_MENU';
export const SHOW_BUSINESS_PARTNER_MENU = 'SHOW_BUSINESS_PARTNER_MENU';
export const HIDE_BUSINESS_PARTNER_MENU = 'HIDE_BUSINESS_PARTNER_MENU';

export const CHANGE_SELECTED_PRODUCT = 'CHANGE_SELECTED_PRODUCT';
export const RESET_SELECTED_PRODUCT = 'RESET_SELECTED_PRODUCT';

export const SET_HELP_WIDGET_AS_LOADED = 'SET_HELP_WIDGET_AS_LOADED';

export const TOGGLE_HELP_WIDGET = 'TOGGLE_HELP_WIDGET';
export const HIDE_HELP_WIDGET = 'HIDE_HELP_WIDGET';

export const HIDE_ALL_MENUS = 'HIDE_ALL_MENUS';
export const TOGGLE_MOBILE_MENU = 'TOGGLE_MOBILE_MENU';

/*
 NAVIGATION
 */
export const CHANGE_CURRENT_APPLICATION = 'CHANGE_CURRENT_APPLICATION';
export const CHANGE_CURRENT_PRODUCT = 'CHANGE_CURRENT_PRODUCT';
export const RESET_CURRENT_APPLICATION = 'RESET_CURRENT_APPLICATION';
export const RESET_CURRENT_PRODUCT = 'RESET_CURRENT_PRODUCT';
