/*
 NAVIGATION
 */
export const CHANGE_CURRENT_APPLICATION_ID = 'CHANGE_CURRENT_APPLICATION_ID';
export const CHANGE_CURRENT_PRODUCT_ID = 'CHANGE_CURRENT_PRODUCT_ID';
export const RESET_CURRENT_APPLICATION_ID = 'RESET_CURRENT_APPLICATION_ID';
export const RESET_CURRENT_PRODUCT_ID = 'RESET_CURRENT_PRODUCT_ID';
